plantaryProject/cart/urls.py
from django.urls import path
from . import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include

app_name = 'cart'

urlpatterns = [
    path('', views.cart_home, name='cart_home'),
    path('cart/', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),
]

plantaryProject/cart/models.py
from django.db import models
from store.models import Product
# Create your models here.
# Cart
class Cart(models.Model):
    objects = models.Manager()
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)
    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return str(self.cart_id)

class CartItem(models.Model):
    objects = models.Manager()
    product = models.ForeignKey(Product, on_delete=models.CASCADE,)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)
    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity 
    
    def __str__(self):
        return str(self.product)

plantaryProject/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from store.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.

def cart_home(request):
    return render(request, 'cart.html')

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id= _cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id = _cart_id(request)
        )
        cart.save()

    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        #if cart_item.quantity < cart_item.product.stock:
        cart_item.quantity +=1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product = product,
            quantity = 1,
            cart = cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')

def cart_detail(request, total=0, counter=0, cart_items = None):
    try:
        cart = Cart.objects.get(cart_id = _cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass

    return render(request, 'cart.html', dict(cart_items = cart_items, total=total, counter=counter))

def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id = _cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def full_remove(request, product_id):
    cart = Cart.objects.get(cart_id = _cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

plantaryProject/cart/templates/cart.html
<!DOCTYPE html>
<html>
<head>

</head>
<body>
    <h1>Cart</h1>
    <div>
        {% if not cart_items %}
            <h1>your shopping cart is empty</h1>
            <p>Please Click <a href="{% url 'storemain' %}"> here</a>to continue shopping. </p>
        {% else %}
            <div>
                <h3>Your Shopping cart</h3>
                <table>
                    <thread class="my_custom_table">
                        <tr>
                            <th colspan="5">
                                Your Items
                            </th>
                        </tr>
                    </thread>
                    <tbody>
                        {% for cart_item in cart_items %}
                            <tr>
                                <td>
                                    <a href="{{cart_item.product.get_absolute_url}}"><img src="{{cart_item.product.image.url}}" alt="" class="float-left rounded custom_image"></a>
                                </td>
                                <td class="text-left">
                                    {{cart_item.product.title}}
                                    <img src = "{{cart_item.product.images.url}}" width="300" height="300" >
                                    <br>
                                    상품: {{cart_item.product.title}}
                                    <br>
                                    개당 가격: {{cart_item.product.price}}원
                                    <br>
                                    수량: {{cart_item.quantity}} x {{cart_item.product.price}}원
                                    <br>
                                    {{cart_item.sub_total}}원
                                    <br>
                                    {% if cart_item.quantity > 0 %}
                                        <a href="{% url 'cart:add_cart' cart_item.product.id %}" >Add</a>&nbsp;                    
                                        <a href="{% url 'cart:cart_remove' cart_item.product.id %}" >Delete</a>&nbsp;
                                        <a href="{% url 'cart:full_remove' cart_item.product.id %}" >Remove</a>
                                    {% else %}
                                        <h1> hello </h1>
                                        &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}">Delete</a>&nbsp;
                                        <a href="{% url 'cart:full_remove' cart_item.product.id %}" >Remove</a>
                                    {% endif %}    
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <table>
                    <thread class="my_custom_thread">
                        <th>Check Out</th>
                    </thread>
                    <tbody>
                        <tr>
                            <td>Please review</td>
                        </tr>
                        <tr>
                            <td>Your total is : {{ total }}원</td>
                        </tr>
                    </tbody>
                </table>
                <a href="{% url 'storemain' %}">쇼핑 계속하기</a>
            </div>
            <div>
                {% if item_count > 0 %}
                    <a href="{% url 'cart:cart_detail' %}">{{item_count}}개의 상품이 담겨있습니다.</a>
                {% endif %}
            </div>
        {% endif %}
</body>
</html>